"""Routers for API entrypoints."""

from .groups import READ_PERMISSION as GROUPS_READ_PERMISSION
from .groups import WRITE_PERMISSION as GROUPS_WRITE_PERMISSION
from .jobs import READ_PERMISSION as JOB_READ_PERMISSION
from .locations import READ_PERMISSION as LOCATIONS_READ_PERMISSION
from .locations import WRITE_PERMISSION as LOCATIONS_WRITE_PERMISSION
from .samples import READ_PERMISSION as SAMPLES_READ_PERMISSION
from .samples import WRITE_PERMISSION as SAMPLES_WRITE_PERMISSION
from .users import READ_PERMISSION as USERS_READ_PERMISSION
from .users import WRITE_PERMISSION as USERS_WRITE_PERMISSION

ENTRYPOINT_PERMISSIONS = (
    GROUPS_READ_PERMISSION,
    GROUPS_WRITE_PERMISSION,
    SAMPLES_READ_PERMISSION,
    SAMPLES_WRITE_PERMISSION,
    LOCATIONS_READ_PERMISSION,
    LOCATIONS_WRITE_PERMISSION,
    USERS_READ_PERMISSION,
    USERS_WRITE_PERMISSION,
    JOB_READ_PERMISSION,
)
