version: '3.9'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - "./volumes/mongodb:/data/db"
    networks:
      - bonsai-net
  api:
    container_name: api
    build: 
      context: server
      network: host
    depends_on:
      - mongodb
    ports: 
      - "8011:8000"
    environment:
      - ALLOWED_ORIGINS=*
    volumes:
      - "./server/app:/usr/src/app/app"
      - "./server/run_mimer.py:/usr/src/app/run_mimer.py"
    networks:
      - bonsai-net
    command: "uvicorn app.main:app --reload --host 0.0.0.0"
  app:
    container_name: app
    build: 
      context: client
      network: host
    depends_on:
      - mongodb
      - api
    ports: 
      - "8010:5000"
    environment:
      - FLASK_APP=app.app:create_app
      - FLASK_ENV=development 
    volumes:
      - "./client/app:/usr/src/app/app"
    networks:
      - bonsai-net
    command: "flask run --host 0.0.0.0"

networks:
  bonsai-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.1.0/24
