version: '3.9'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services: 
  mongodb:
    image: mongo:4.4.22
    container_name: bonsai_mongodb
    ports:
      - "8813:27017"
    expose:
      - "27017"
    volumes:
      - "./volumes/mongodb:/data/db"
    networks:
      - markus-bonsai-net

  redis:
    image: redis:7.0.10
    networks:
      - markus-bonsai-net

  api:
    container_name: bonsai_api
    build: 
      context: api
      network: host
    depends_on:
      - mongodb
    ports: 
      - "8811:8000"
    environment:
      - ALLOWED_ORIGINS=*,*.lund.skane.se,mtlucmds2.lund.skane.se
      - DB_HOST=mongodb
      - REDIS_HOST=redis
    volumes:
      - "./api/app:/home/worker/app/app"
    networks:
      - markus-bonsai-net
    command: "uvicorn app.main:app --reload --log-level debug --host 0.0.0.0"

  app:
    container_name: bonsai_app
    build: 
      context: frontend
      network: host
    depends_on:
      - mongodb
      - api
      - minhash_service
    ports: 
      - "8812:5000"
    environment:
      - FLASK_APP=app.app:create_app
      - FLASK_ENV=development 
      - "BONSAI_API_URL=http://mtlucmds2.lund.skane.se:8811"
    volumes:
      - "./frontend/app:/home/worker/app/app"
    networks:
      - markus-bonsai-net
    command: "flask run --debug --host 0.0.0.0"

  minhash_service:
    container_name: minhash_service
    build: 
      context: minhash_service
      network: host
    depends_on:
      - mongodb
      - api
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - "./minhash_service/minhash_service:/home/worker/app/minhash_service"
      - "./volumes/api/genome_signatures:/data/signature_db"
    networks:
      - markus-bonsai-net
    command: "minhash_service"

  allele_cluster_service:
    container_name: allele_cluster_service
    build: 
      context: allele_cluster_service
      network: host
    depends_on:
      - mongodb
      - api
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - "./allele_cluster_service/allele_cluster_service:/home/worker/app/allele_cluster_service"
    networks:
      - markus-bonsai-net
    command: "cluster_service"

networks:
  markus-bonsai-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.30.0/24
