version: "3.9"
services:

  chrome:
    container_name: chrome
    hostname: chrome
    image: selenium/standalone-chrome
    platform: linux/x86_64
    shm_size: 2gb
    privileged: true
    ports:
     - "4444:4444"
     - "8812:7900"
    networks:
     - bonsai-net

  ete-tests:
    container_name: ete-tests
    build: 
      context: ete_tests
    volumes:
     - ./ete_tests/tests/:/home/worker/app/tests
     - ./ete_tests/config.yml:/home/worker/app/config.yml
     - ./test_reports:/home/worker/app/reports:rw
    depends_on:
     - chrome
     - api
     - frontend
    networks:
     - bonsai-net
    command: pytest --html=reports/bonsai_ete_report.html --self-contained-html tests

  api:
    volumes:
      - "./api/bonsai_api:/home/worker/app/bonsai_api"
      - "./ete_tests/tests/fixtures/minhash_signatures:/data/signature_db"
      - "./ete_tests/setup_bonsai_database.sh:/tmp/setup_bonsai_database.sh"
    entrypoint: /tmp/setup_bonsai_database.sh