version: '3.9'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - "./volumes/mongodb:/data/db"
    networks:
      - bonsai-net

  redis:
    image: redis:7.0.10
    networks:
      - bonsai-net

  api:
    container_name: api
    build: 
      context: api
      network: host
    depends_on:
      - mongodb
      - minhash_service
      - allele_cluster_service
    ports: 
      - "8011:8000"
    environment:
      - ALLOWED_ORIGINS=*
    volumes:
      - "./api/app:/home/worker/app/app"
    networks:
      - bonsai-net
    command: "uvicorn app.main:app --reload --host 0.0.0.0"

  frontend:
    container_name: frontend
    build: 
      context: frontend
      network: host
    depends_on:
      - mongodb
      - api
    ports: 
      - "8010:5000"
    environment:
      - FLASK_APP=app.app:create_app
      - FLASK_ENV=development 
    volumes:
      - "./frontend/app:/home/worker/app/app"
    networks:
      - bonsai-net
    command: "flask run --host 0.0.0.0"

  minhash_service:
    container_name: minhash_service
    build: 
      context: minhash_service
      network: host
    depends_on:
      - redis
    volumes:
      - "./minhash_service/minhash_service:/home/worker/app/app"
      - "./volumes/api/genome_signatures:/data/signature_db"
    networks:
      - bonsai-net
    command: "minhash_service"

  allele_cluster_service:
    container_name: allele_cluster_service
    build: 
      context: allele_cluster_service
      network: host
    depends_on:
      - redis
    volumes:
      - "./allele_cluster_service/allele_cluster_service:/home/worker/app/app"
    networks:
      - bonsai-net
    command: "cluster_service"

networks:
  bonsai-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.20.0/24
