[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[mypy]
plugins = "pydantic.mypy"

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]

[tool.pytest_env]
API_AUTHENTICATION = false